config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "books#index"
  resources :books, only: [:index,:show] do
  end
  resources :end_books, only: [:create]
  resources :users, only: [:index,:show] do
    collection do
      get "search"
    end
    resources :user_books,only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :end_books, dependent: :destroy
  
  has_many :users, through: :end_books

  ##function

  def readover?(user)
    self.users.include?(user)
  end

end

app/models/end_book.rb
class EndBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :user_id,:book_id,:comments,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum status: [:men,:lady]
  has_many :end_books, dependent: :destroy
  has_many :books, through: :end_books


  validates :name ,presence: true

  def birth #年月日に変換
   self.birth_day.strftime("%Y年 %m月 %d日")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name,:sex,:birth_day])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.limit(4)
    @subbooks = Book.where("id > ? and id < ?", 4, 8) ##4超過8未満
  end

  def show;@book = Book.find(params[:id]);end
end

app/controllers/end_books_controller.rb
class EndBooksController < ApplicationController
  before_action :authenticate_user!

  def create
    @readover = Book.find(get_book)
    unless @readover.readover?(current_user)
      r = @readover.end_books.new(comments: comments_params,user_id: current_user.id)
      if r.save
        respond_to do |f|
          f.js
        end
      end
    end
  end

end

private

def get_book
  params.require(:end_book)[:book_id]
end

def comments_params
  params.require(:end_book)[:comments]
end

####
# js.erbの使い方を学びviewを実装

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController
  def show
    @user = User.find(params[:user_id])
    @book = @user.end_books.find_by(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index ##一覧
    @users = User.limit(10)
  end

  def show;@user = User.find(params[:id]);end

  def search #検索時
  end

  def user_book
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/end_books_helper.rb
module EndBooksHelper
end

app/helpers/user_books_helper.rb
module UserBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<div class="main-layout">
  <div class="main-layout-contents">
    <% @books.each do |book| %>
      <div class="book">
        <div class="book-image-content">
          <a href="<%= book_path book.id  %>">
          <div class="book-image-box">
            <%= image_tag "#{book.id}.jpg" ,alt: "タイトル",class: "book-image" %>
          </div>
          </a>
        </div>
      </div>
    <% end %>
  </div>
  
  <div class="main-layout-contents">
    <% @subbooks.each do |book| %>
        <div class="book">
          <div class="book-image-content">
            <a href="<%= book_path book.id  %>">
            <div class="book-image-box">
              <%= image_tag "#{book.id}.jpg" ,alt: "タイトル",class: "book-image" %>
            </div>
            </a>
          </div>
        </div>
      <% end %>
  </div>
</div>

<div class="nav-footer">
  <div class="center-footer">
    <div class="center-accessibility">
      <div class="accessibility-top">
        <%= link_to "book-listについて","#",style: "color:white;text-decoration:none;" %>
      </div>
      <div class="accessibility-box">
        <%= link_to "情報","#",style: "color:white;text-decoration:none;" %>
      </div>
      <div class="accessibility-box">book-listとは</div>
      <div class="accessibility-box">book-listの地域</div>
    </div>
    <div class="center-accessibility">
      <div class="accessibility-top">
        <%= link_to "bookとは","#",style: "color:white;text-decoration:none;" %>
      </div>
      <div class="accessibility-box">
        <%= link_to "おまけとは","#",style: "color:white;text-decoration:none;" %>
      </div>
      <div class="accessibility-box">test</div>
      <div class="accessibility-box">test</div>
    </div>
    <div class="center-accessibility">
      <div class="accessibility-top">
        <%= link_to "bookとは","#",style: "color:white;text-decoration:none;" %>
      </div>
      <div class="accessibility-box">
        <%= link_to "余白","#",style: "color:white;text-decoration:none;" %>
      </div>
      <div class="accessibility-box">コンテンツ関係</div>
      <div class="accessibility-box">ヘルプ</div>
    </div>
    <div class="center-accessibility">
      <div class="accessibility-box"></div>
      <div class="accessibility-box"></div>
      <div class="accessibility-box"></div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="book-show">
  <div class="left">
    <div class="img-box">
      <div class="img-wrapper">
        <div class="img-canvas">
          <%= image_tag "#{@book.id}.jpg" ,alt: "タイトル",class: "img-book" %>
        </div>
      </div>
    </div>
  </div>
  <div class="center">
    <div class="book-title">
      <h1 class="title">
        <span>
          <%= @book.title %>
        </span>
        <span>
          <%= @book.date %>
        </span>
      </h1>
    </div>
    <div class="book-author">
      <%= @book.author %>
    </div>
    <hr>
    <div class="book-outline">
      <div class="book-digest">
        本の説明
      </div>
      <div class="book-summary">
        <%= @book.summary %>
      </div>
    </div>
  </div>
  <br>
  ここにend_buttonをおく
  <div id="over">
  <%= render "end_books/readover",book: @book%>
  </div>
</div>

app/views/end_books/_readover.html.erb
<%if user_signed_in? %>
  <% if book.readover?(current_user)  %> <%##trueがover falseがunread%>
      <%= link_to "☑️","#"%>
      <%# <% current_user.end_books.find_by(book_id: book.id).comments %>
      <%# 書いた人の本の内容が見たいわけ## %>

  <% else %>
    <%= form_with model: book.end_books ,url: end_books_path do |f|%>
      <%= f.hidden_field :book_id,value: book.id %>
      <%= f.text_area :comments,required: true,cols: 25,rows: 4,placeholder: "この本の感想を簡単に入力してください" %>
      <%= f.submit "読了する"%>
    <% end %>
  <% end %>
<% end %>

app/views/end_books/create.js.erb
$("#over").html("<%= j(render "end_books/readover", book: @readover) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div id="booklist">
      <%= link_to "BookList",root_path,class: "booklist" %>
    </div>
    <div id="navbox-container">
      <%= form_with id: "navform" do |f|%>
        <div class="nav-fill">
          <%# <%= f.text_field :name %> %>
        </div>
        <div class="nav-right">
          <div class="nav-search-submit nav-sprite">
          <span id="nav-search-submit-text" class="nav-search-submit-text nav-sprite">
          </span>
            <%# <%= f.submit type: "submit",class:"nav-input" ,value:"検索" ,tabindex:"10" %> %>
          </div>
        </div>
      <% end %>
      </div>
    <div id="navbox-container">
      <%= form_with id: "navform" do |f|%>
        <div class="nav-fill">
          <%# <%= f.text_field :name %> %>
        </div>
        <div class="nav-right">
          <div class="nav-search-submit nav-sprite">
          <span id="nav-search-submit-text" class="nav-search-submit-text nav-sprite">
          </span>
          <%# <%= f.submit type: "submit",class:"nav-input" ,value:"検索" ,tabindex:"10" %> %>
          </div>
        </div>
    <% end %>
    </div>

    <%if user_signed_in? %>
    <button class="header_btn">
      <%= link_to "#{current_user.name}さんのMYPAGE", user_path(current_user),class: "btn_mypage" %>
    </button>
    <button class="header_btn">
      <%= link_to "ログアウト", destroy_user_session_path,method: :delete ,class: "btn_logout" %>
    </button>
    <% else %>
    <button class="header_btn">
      <%=  link_to "ログイン", user_session_path,class: "btn_login" %>
    </button>
    <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/user_books/show.html.erb
<div class="book-show">
  <div class="left">
    <div class="img-box">
      <div class="img-wrapper">
        <div class="img-canvas">
          <%= image_tag "#{@book.id}.jpg" ,alt: "タイトル",class: "img-book" %>
        </div>
      </div>
    </div>
  </div>
  <div class="center">
    <div class="book-title">
      <h1 class="title">
        <span>
          <%= @book.book.title %>
        </span>
        <span>
          <%= @book.book.date %>
        </span>
      </h1>
    </div>
    <div class="book-author">
      <%= @book.book.author %>
    </div>
    <hr>
    <div class="book-outline">
      <div class="book-digest">
        <%= @user.name %>さんの本の感想
      </div>
      <div class="book-summary">
        <%= @book.comments %>
      </div>
    </div>
  </div>
  <br>
</div>

app/views/users/show.html.erb
<div class="name">
  <div class="name-content"><%= @user.name %>さんのpage</div>
</div>
  <div class="yourends">
  <% if @user.end_books.present? %>
    <div class="yourends-center">
      <div class="yourends-center-year">
      </div>
      <div class="yourends-center-books">
          <%if current_user.id == params[:id].to_i %> <%#自分のmypage%>
            <% @user.end_books.each do |info_user_books| %>
              <div class="book-content">
                <div class="book-content-left">
                  <% info_books = Book.find(info_user_books.book_id) %>
                  <div class="book-content-img">
                    <%= link_to book_path info_books.id  do %>
                      <%= image_tag "#{info_books.id}.jpg" ,alt: "タイトル",class: "critical-img" %>
                    <% end %>
                  </div>
                </div>
                <div class="book-content-center">
                  <div class="book-content-row"><%= info_books.title %></div>   
                  <div class="book-content-row">(著): <%= info_books.author %></div>   
                  <div class="book-content-row">読了日時: <%= info_user_books.created_at %></div>
                </div>
                <div class="book-content-right">
                  <div class="book-content-row row-list">この本の感想</div>   
                  <div class="book-content-review">　<%= info_user_books.comments %></div>
                </div>
              </div>
            <% end %>
          <% else %>
            <% @user.end_books.each do |info_user_books| %> <%#他人のmypage%>
            <% info_books = Book.find(info_user_books.book_id) %>
              <div class="book-content">
                <div class="book-content-left">
                  <div class="book-content-img">
                    <%= link_to user_user_book_path(params[:id],info_books.id)  do %>
                      <%= image_tag "#{info_books.id}.jpg" ,alt: "タイトル",class: "critical-img" %>
                    <% end %>
                  </div>
                </div>
                <div class="book-content-right">
                  <div class="book-content-row"><%= info_books.title %></div>   
                  <div class="book-content-row">(著): <%= info_books.author %></div>   
                  <div class="book-content-row">読了日時: <%= info_user_books.created_at %></div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>